import mktagle from '../../function/mktagle'
import { AVCodecID } from 'avutil/codec'

export const WavTag2CodecId = {
  0x0001: AVCodecID.AV_CODEC_ID_PCM_U8,
  0x0002: AVCodecID.AV_CODEC_ID_ADPCM_MS,
  0x0003: AVCodecID.AV_CODEC_ID_PCM_F32LE,
  0x0006: AVCodecID.AV_CODEC_ID_PCM_ALAW,
  0x0007: AVCodecID.AV_CODEC_ID_PCM_MULAW,
  0x000A: AVCodecID.AV_CODEC_ID_WMAVOICE,
  0x0010: AVCodecID.AV_CODEC_ID_ADPCM_IMA_OKI,
  0x0011: AVCodecID.AV_CODEC_ID_ADPCM_IMA_WAV,
  0x0017: AVCodecID.AV_CODEC_ID_ADPCM_IMA_OKI,
  0x0020: AVCodecID.AV_CODEC_ID_ADPCM_YAMAHA,
  0x0022: AVCodecID.AV_CODEC_ID_TRUESPEECH,
  0x0031: AVCodecID.AV_CODEC_ID_GSM_MS,
  0x0032: AVCodecID.AV_CODEC_ID_GSM_MS,
  0x0038: AVCodecID.AV_CODEC_ID_AMR_NB,
  0x0042: AVCodecID.AV_CODEC_ID_G723_1,
  0x0045: AVCodecID.AV_CODEC_ID_ADPCM_G726,
  0x0014: AVCodecID.AV_CODEC_ID_ADPCM_G726,
  0x0040: AVCodecID.AV_CODEC_ID_ADPCM_G726,
  0x0061: AVCodecID.AV_CODEC_ID_ADPCM_IMA_DK4,
  0x0062: AVCodecID.AV_CODEC_ID_ADPCM_IMA_DK3,
  0x0064: AVCodecID.AV_CODEC_ID_ADPCM_G726,
  0x0069: AVCodecID.AV_CODEC_ID_ADPCM_IMA_WAV,
  0x0075: AVCodecID.AV_CODEC_ID_METASOUND,
  0x0083: AVCodecID.AV_CODEC_ID_G729,
  0x00ff: AVCodecID.AV_CODEC_ID_AAC,
  0x0111: AVCodecID.AV_CODEC_ID_G723_1,

  // ADTS AAC
  0x1600: AVCodecID.AV_CODEC_ID_AAC,
  0x1602: AVCodecID.AV_CODEC_ID_AAC_LATM,
  0x2000: AVCodecID.AV_CODEC_ID_AC3
}

export const codecBmpTags: Record<int32, AVCodecID> = {
  [mktagle('H264')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('h264')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('X264')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('x264')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('avc1')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('DAVC')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('SMV2')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('VSSH')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('Q264')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('V264')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('GAVC')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('UMSV')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('tshd')]: AVCodecID.AV_CODEC_ID_H264,
  [mktagle('INMC')]: AVCodecID.AV_CODEC_ID_H264,

  [mktagle('FMP4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DIVX')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DX50')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('XVID')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('MP4S')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('M4S2')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DIVX')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [0x04 as int32]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('ZMP4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DIV1')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('BLZ0')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('mp4v')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('UMP4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('WV1F')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('SEDG')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('RMP4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('3IV2')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('WAWV')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('FFDS')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('FVFW')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DCOD')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('MVXM')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('PM4V')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('SMP4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DXGM')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('VIDM')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('M4T3')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('GEOX')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('G264')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('HDX4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DM4V')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DMK2')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DYM4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DIGI')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('EPHV')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('EM4A')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('M4CC')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('SN40')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('VSPX')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('ULDX')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('GEOV')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('SIPP')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('SM4V')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('XVIX')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('DreX')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('QMP4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('PLV1')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('GLV4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('GMP4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('MNM4')]: AVCodecID.AV_CODEC_ID_MPEG4,
  [mktagle('GTM4')]: AVCodecID.AV_CODEC_ID_MPEG4,

  [mktagle('MPG4')]: AVCodecID.AV_CODEC_ID_MSMPEG4V1,
  [mktagle('MP41')]: AVCodecID.AV_CODEC_ID_MSMPEG4V1,
  [mktagle('MP42')]: AVCodecID.AV_CODEC_ID_MSMPEG4V2,
  [mktagle('DIV2')]: AVCodecID.AV_CODEC_ID_MSMPEG4V2,
  [mktagle('MP43')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('DIV3')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('MPG3')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('DIV5')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('DIV6')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('DIV4')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('DVX3')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('AP41')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('COL1')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,
  [mktagle('COL0')]: AVCodecID.AV_CODEC_ID_MSMPEG4V3,

  [mktagle('VP80')]: AVCodecID.AV_CODEC_ID_VP8,
  [mktagle('VP90')]: AVCodecID.AV_CODEC_ID_VP9
}
